### ISSUE TITLE
Default Login Not Working

### ISSUE THREAD

**Issue by Pingblue** [linuxserver/docker-pyload#6] opened 2020-03-12 13:37 UTC
The default login doesn't appear to be working, admin/password

**Comment by thelamer** [comment] 2020-03-15 18:08
I cannot replicate this, please create a clean container and try again. 
As this is not a bug report I will be closing this, if you need further support please use discord/discourse as outlined in the issue template.

**Closed as completed by thelamer** 2020-03-15 18:08 UTC
